source 'https://rubygems.org'

gem 'jekyll'
gem 'json'
gem 'jekyll-assets'
gem 'sass'
gem 'font-awesome-sass'
gem 'uglifier'
gem 'activesupport'
gem 'jekyll-last-modified-at'
gem 'yajl-ruby', '~> 1.3.1'
gem 'rake'